name: pixl.js-fw

on:
  push:
    branches: [ "develop", "neo_v2"]
    tags:  ["*"]
  pull_request:
    types: ["opened"]
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        board: ["LCD", "OLED", "NEO"]
    runs-on: ubuntu-latest
    container: solosky/nrf52-sdk:latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Change Owner of Container Working Directory
      run: chown root:root .
    - name: build firmware
      run: cd fw && make all RELEASE=1 APP_VERSION=$GITHUB_RUN_NUMBER BOARD=${{matrix.board}}
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pixljs_fw_${{matrix.board}}
        path: |
          fw/_build/bootloader.hex
          fw/_build/pixljs.hex
          fw/_build/pixljs_all.hex
          fw/_build/pixjs_ota_v${{github.run_number}}.zip
          fw/docs/fw_readme.txt
          fw/scripts/fw_update.bat